### PR TITLE
Added FEATURES option to corrosion_import_crate

### LINKED ISSUE #57: Selectively import crates
There should be a way to filter the imported crates from a workspace.

Something like:
```cmake
corrosion_import_crate(
    MANIFEST_PATH Cargo.toml
    CRATES foo)
```

cc @ogoffart

**EDIT:** Additionally, corrosion_import_crate should only import the crates in the target manifest, not for the whole workspace.

### PR DESCRIPTION
**Pull request by kwek20**
Fixed #57 part 2. 

I have not yet managed to solve the features using `set_property`

### CODE REVIEW

**Comment by kwek20** [comment]
Apparently the set_property restriction for interfaces is removed in 3.19.x, but still couldnt get it to work though
 `get_target_property() called with non-existent target "rust-lib"`
 
 Any ideas @AndrewGaspar ?

**Comment by ogoffart** [comment]
I think being able to set the features is indeed needed. I'm probably going to make use of that at some point.

I'm just afraid that the way this is implemented in this patch doesn't work well with workspace manifest where one select only a crate, and want to enable features for that one crate.

**Comment by tronical** [comment]
What's the restriction you're running into with `set_property`?

In #102 I have a patch for review that kind of works similar to that, allowing the user to set a custom property on the targets created by `corrosion_import_crate` which is passed on to the cargo build.

If there was a `CORROSION_FEATURES` property, then perhaps it could be added to the cargo command line by passing the feature list to the generator using `$<TARGET_PROPERTY:${target_name},CORROSION_FEATURES>` ?

**Comment by kwek20** [comment]
Hi guys! Thanks for the feedback, I do not recall why it didnt work, im pretty new to cmake so it could just be i did it wrong .)
I wont have time to fix it in the coming 3 weeks, but after that I can give it another shot

**Comment by tronical** [comment]
Hi! I've taken @kwek20 's initial commit and changed it to use a target property and submitted it as #108

**Comment by kwek20** [comment]
Oooh! Ill give it a test! Thanks man.. you know how life gets in the way of things :) @tronical

**Comment by tronical** [comment]
> Oooh! Ill give it a test! Thanks man.. you know how life gets in the way of things :) @tronical

Haha yeah, I know that feeling :)

**Pull request closed without merging**
