### PR TITLE
Change install path from /usr/Corrosion to /usr

### PR DESCRIPTION
**Pull request by 2xsaiko**
cmake should be able to find the cmake module if installed normally using make install.

### CODE REVIEW

**Comment by AndrewGaspar** [comment]
This has been brought up before... https://github.com/AndrewGaspar/corrosion/issues/52

The install path that is used by Corrosion should be found by CMake when calling `find_package(Corrosion)`, without changing any default install paths or environment variables or anything. Could you explain in more detail what the exact problem you're running into is and maybe I can help you debug?

**Comment by 2xsaiko** [comment]
Hmm, maybe I've done something wrong when installing since I didn't do it with just make install, instead writing an ebuild for it.

Still though, /usr/Corrosion is not a standard install path and it most likely won't be officially packaged like that in any distro. (I just noticed because portage yelled at me that the package installed into non-standard paths.) Why is it installing to there, anyways? Any other cmake plugin installs into /usr/share/cmake (etc.) too.

**Comment by AndrewGaspar** [comment]
> Why is it installing to there, anyways? Any other cmake plugin installs into /usr/share/cmake (etc.) too.

CMake recognizes it as a universal install path that works on both Unix and Windows without having to do any platform-specific behavior. https://cmake.org/cmake/help/latest/command/find_package.html?highlight=find_package#search-procedure

If this package was installing any executables or libraries that would be directly consumed by users, I'd understand your concern, but this package should _only_ be consumed by CMake, so I don't see any reason why it would even need to install its executables directly into $PREFIX/libexec or similar.

This behavior also has the benefit of making the package trivially relocatable, for some marginal benefit.

I can see package managers not liking things to be installed outside `bin`, `lib`, `libexec`, etc. If you make this change a non-default option, I could merge that.

You'll need to update `CorrosionConfig.cmake.in`, too: https://github.com/AndrewGaspar/corrosion/blob/master/cmake/CorrosionConfig.cmake.in

**Comment by AndrewGaspar** [comment]
Made defunct by #78. Thank you for the PR!

**Pull request closed without merging**
