### PR TITLE
Fix toolchain resolution "override" regex

### LINKED ISSUE #81: Toolchain resolution breaks when default toolchain is overridden
### Steps to reproduce:
- Create `build` folder.
- Run `rustup override set nightly` in it.
- Try building the project.

### Result:
```
CMake Error at /home/egeretto/XXX/build/_deps/corrosion-src/cmake/FindRust.cmake:166 (find_program):
  Could not find Rust_CARGO_CACHED using the following names: cargo
Call Stack (most recent call first):
  /home/egeretto/XXX/build/_deps/corrosion-src/cmake/Corrosion.cmake:11 (find_package)
  /home/egeretto/XXX/build/_deps/corrosion-src/CMakeLists.txt:39 (include)
```

### Cause:
When running in a folder with an overridden toolchain, the output of `rustup toolchain list --verbose` looks like the following:
```
stable-x86_64-unknown-linux-gnu (default)	/home/egeretto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (override)	/home/egeretto/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
```

However, the following regex does not take the `(override)` into account:
https://github.com/AndrewGaspar/corrosion/blob/2e4c62c9f001487b485c2f8c923dba348607b41c/cmake/FindRust.cmake#L96

### PR DESCRIPTION
**Pull request by acidghost**
This fixes #81.

Makes it so that the `rustup toolchain list --verbose` is parsed correctly during toolchain resolution. The overridden toolchain was interfering with the parsing.

### CODE REVIEW

**Comment by acidghost** [comment]
@AndrewGaspar these checks are failing for reasons outside this PR.

**Comment by AndrewGaspar** [comment]
Ah, that's irritating. Getting annoyed with how unstable the GitHub Actions environment is...

**Comment by AndrewGaspar** [comment]
Finally got the CI fixed, sorry for the delay! Been busy with job interviews. I got the job, though!

So my reading of this PR is that the "default" toolchain is used in the presence of an override. Wouldn't it make more sense to use the "override" toolchain when it's present? That would make more sense to me. What do you think?

**Comment by acidghost** [comment]
Thanks for the help and good luck on your new job! :)

Indeed it would make more sense. I'll update and test the PR later today.

**Comment by acidghost** [comment]
> So my reading of this PR is that the "default" toolchain is used in the presence of an override. Wouldn't it make more sense to use the "override" toolchain when it's present? That would make more sense to me. What do you think?

@AndrewGaspar finally got to it :sweat_smile:

Tested with the following Dockerfile (rust-toolchain is really any `cargo new`):

```dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
 && apt-get -y install \
        build-essential \
        cmake \
        curl \
        ninja-build \
 && rm -rf /var/lib/apt/lists/* \
 && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
        sh -s -- -y --profile minimal --default-toolchain "stable"

WORKDIR /work
COPY . .

RUN . $HOME/.cargo/env \
 && cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release \
        -DCORROSION_BUILD_TESTS=ON --log-level=DEBUG \
 && cmake --build build --config Release \
 && cmake --install build --config Release \
 && cd test/rust-toolchain \
 && rustup override set 1.48 \
 && cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release --log-level=DEBUG \
 && cmake --build build --config Release
```

**Comment by acidghost** [comment]
@AndrewGaspar Just a gentle reminder :)

**Comment by ogoffart** [comment]
This pr adds a lot of `message(...` that should probably be removed

**Comment by acidghost** [comment]
These are `DEBUG` messages, so should not appear with less verbose log levels.

If you want me to remove them I'll do it.

**Comment by ogoffart** [comment]
> If you want me to remove them I'll do it.

Yeah, i'm not a fan of keeping lots of debugging statements in production code.

**Comment by acidghost** [comment]
@ogoffart Done.

Next time we need to debug something we're going to have to re-add these statements. Not sure if it's more productive re-adding these `DEBUG`-only log statements or just passing `--log-level` to `cmake` whenever you need them..

**Pull request merged**
