### PR TITLE
Install Corrosion directly to GNU install locations on Unix platforms

### PR DESCRIPTION
**Pull request by AndrewGaspar**
By popular demand, this changes Corrosion to install directly into the GNU install locations rather than in a Corrosion directory when installing on a Unix system. It maintains the previous behavior on Windows.

### CODE REVIEW

**Comment by AndrewGaspar** [comment]
cc @JBBgameich @2xsaiko @humenda

**Comment by JBBgameich** [comment]
Thank you :)

**Comment by humenda** [comment]
Also thanks from my side :)

**Comment by 2xsaiko** [comment]
Thanks!

**Pull request merged**
